CREATE DATABASE AGENCIA;
USE AGENCIA;

CREATE TABLE CLIENTE (
  idCLIENTE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL  ,
  SOBRENOME VARCHAR(70) NOT NULL  ,
  DATA_NASCIMENTO DATE  NOT NULL  ,
  EMAIL VARCHAR(45)  NOT NULL  ,
  TELEFONE VARCHAR(11)  NOT NULL    ,
PRIMARY KEY(idCLIENTE)
);


CREATE TABLE PACOTE_VIAGEM (
  idPACOTE_VIAGEM INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL  ,
  DESCRICAO VARCHAR(255) NOT NULL  ,
  DESTINO VARCHAR(45)  NOT NULL  ,
  DURACAO VARCHAR(20)  NOT NULL  ,
  PRECO FLOAT  NOT NULL  ,
  DATA_PARTIDA DATE  NOT NULL  ,
  DATA_RETORNO DATE  NOT NULL    ,
PRIMARY KEY(idPACOTE_VIAGEM)
);

CREATE TABLE RESERVAS (
  idRESERVAS INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  PACOTE_VIAGEM_idPACOTE_VIAGEM INTEGER UNSIGNED  NOT NULL  ,
  CLIENTE_idCLIENTE INTEGER UNSIGNED  NOT NULL  ,
  DATA_RESERVA DATE NOT NULL  ,
  STATUS_2 VARCHAR(30) NOT NULL    ,
PRIMARY KEY(idRESERVAS)  ,
INDEX RESERVAS_FKIndex1(CLIENTE_idCLIENTE)  ,
INDEX RESERVAS_FKIndex2(PACOTE_VIAGEM_idPACOTE_VIAGEM)
);


CREATE TABLE PAGAMENTOS (
  idPAGAMENTOS INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  RESERVAS_idRESERVAS INTEGER UNSIGNED  NOT NULL  ,
  VALOR FLOAT  NOT NULL  ,
  DATA_PAGAMENTO DATE  NOT NULL  ,
  METODOS VARCHAR(45)  NOT NULL    ,
PRIMARY KEY(idPAGAMENTOS)  ,
INDEX PAGAMENTOS_FKIndex1(RESERVAS_idRESERVAS)
);

INSERT INTO CLIENTE(NOME,SOBRENOME,DATA_NASCIMENTO,EMAIL,TELEFONE) VALUES('Antonio','Tavares', '2007-01-29', 'antoniomatapombo@gmail.com', '71988363423');
INSERT INTO CLIENTE(NOME,SOBRENOME,DATA_NASCIMENTO,EMAIL,TELEFONE) VALUES('Nelsimara', 'Souza', '1983-08-07', 'nelsinhapipoquinha@gmail.com', '71987220267');
INSERT INTO CLIENTE(NOME,SOBRENOME,DATA_NASCIMENTO,EMAIL,TELEFONE) VALUES('Sandra', 'Maximinho', '2023-09-24', 'maximinhomother@gmail.com', '71986134859');

INSERT INTO PACOTE_VIAGEM(NOME,DESCRICAO,DESTINO,DURACAO,PRECO,DATA_PARTIDA,DATA_RETORNO) VALUES ('PREMIUM', 'vá e não volte', 'Acajaru', '5 dias', '345.23','2025-08-14','2012-05-12');
INSERT INTO PACOTE_VIAGEM(NOME,DESCRICAO,DESTINO,DURACAO,PRECO,DATA_PARTIDA,DATA_RETORNO) VALUES('MASTER' , 'cuidado chegou a chapa', 'Metron','2 dias', '50.25', '2024-04-02', '2024-04-04');
INSERT INTO PACOTE_VIAGEM(NOME,DESCRICAO,DESTINO,DURACAO,PRECO,DATA_PARTIDA,DATA_RETORNO) VALUES('POBRE', 'ana mora lá', 'Mangueira', '1 dia', '5.20','2024-04-02', '2024-04-03');

select  * from cliente;
select  * from pacote_viagem;

INSERT INTO RESERVAS(PACOTE_VIAGEM_idPACOTE_VIAGEM ,CLIENTE_idCLIENTE ,DATA_RESERVA  ,STATUS_2  ) VALUES (1,1, '2024-04-03','CONFIRMADA');
INSERT INTO RESERVAS(PACOTE_VIAGEM_idPACOTE_VIAGEM ,CLIENTE_idCLIENTE ,DATA_RESERVA  ,STATUS_2  ) VALUES (2,2, '2024-04-05','PENDENTE');
INSERT INTO RESERVAS(PACOTE_VIAGEM_idPACOTE_VIAGEM ,CLIENTE_idCLIENTE ,DATA_RESERVA  ,STATUS_2  ) VALUES (3,3, '2024-04-06','CANCELADA');
select  * from reservas;

DELETE FROM RESERVAS WHERE idRESERVAS = 1;

UPDATE CLIENTE SET NOME = 'Victor' where idCLIENTE = 1;

INSERT INTO PAGAMENTOS( RESERVAS_idRESERVAS ,VALOR ,DATA_PAGAMENTO,METODOS) VALUES (1,'345.23','2024-12-06','DEBITO');
INSERT INTO PAGAMENTOS( RESERVAS_idRESERVAS ,VALOR ,DATA_PAGAMENTO,METODOS) VALUES (2,'50.25','2025-05-09','PIX');
INSERT INTO PAGAMENTOS( RESERVAS_idRESERVAS ,VALOR ,DATA_PAGAMENTO,METODOS) VALUES (3,'5.20','2012-05-09','CREDITO');
select * from pagamentos;