create database cinema;
use cinema;

CREATE TABLE CINEMA (
  idCINEMA INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  NOME VARCHAR(50)  NULL  ,
  SALA INTEGER UNSIGNED  NULL  ,
  CAPACIDADE INTEGER UNSIGNED  NULL  ,
  CIDADE VARCHAR(50)  NULL    ,
PRIMARY KEY(idCINEMA));

CREATE TABLE FILMES (
  idFILMES INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  TITULO VARCHAR(100)  NULL  ,
  GENERO VARCHAR(100)  NULL  ,
  CENSURA VARCHAR(5)  NULL    ,
PRIMARY KEY(idFILMES));

CREATE TABLE SESSAO (
  idSESSAO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  FILMES_idFILMES INTEGER UNSIGNED  NOT NULL  ,
  CINEMA_idCINEMA INTEGER UNSIGNED  NOT NULL  ,
  DATA_HORA DATETIME  NULL  ,
  PRECO FLOAT  NULL    ,
PRIMARY KEY(idSESSAO)  ,
INDEX SESSAO_FKIndex1(CINEMA_idCINEMA)  ,
INDEX SESSAO_FKIndex2(FILMES_idFILMES));

CREATE TABLE CLIENTES (
  idCLIENTES INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  NOME VARCHAR(100)  NULL  ,
  CPF VARCHAR(11)  NULL  ,
  SEXO CHAR  NULL  ,
  DATA_NASCIMENTO DATE  NULL    ,
PRIMARY KEY(idCLIENTES));

CREATE TABLE COMPRAS (
  idCOMPRAS INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  SESSAO_idSESSAO INTEGER UNSIGNED  NOT NULL  ,
  CLIENTES_idCLIENTES INTEGER UNSIGNED  NOT NULL  ,
  QUANTIDAE_INTEIRA INTEGER UNSIGNED  NULL  ,
  QUANTIDAE_MEIA INTEGER UNSIGNED  NULL  ,
  FORMA_PAGAMENTO VARCHAR(50)  NULL    ,
PRIMARY KEY(idCOMPRAS)  ,
INDEX COMPRAS_FKIndex1(CLIENTES_idCLIENTES)  ,
INDEX COMPRAS_FKIndex2(SESSAO_idSESSAO));

INSERT INTO CINEMA (NOME,SALA,CAPACIDADE,CIDADE) values("CINEMARK", 3, 70, "SALVADOR");
INSERT INTO CINEMA (NOME,SALA,CAPACIDADE,CIDADE) values("VITORMARK", 4, 80, "CAMAÇARI");
INSERT INTO CINEMA (NOME,SALA,CAPACIDADE,CIDADE) values("VITOPOLIS", 5, 75, "LAURO DE FREITAS");
INSERT INTO CINEMA (NOME,SALA,CAPACIDADE,CIDADE) values("LAPACINES", 4, 80, "CAMAÇARI");
INSERT INTO CINEMA (NOME,SALA,CAPACIDADE,CIDADE) values("SALVADOR CINEMAS", 10, 130, "SALVADOR");

SELECT * FROM CINEMA;

INSERT INTO FILMES (TITULO ,GENERO  ,CENSURA) VALUES("VICTOR E AS AVENTURAS COM PINGO", "AÇÃO", "LIVRE");
INSERT INTO FILMES (TITULO ,GENERO  ,CENSURA) VALUES("IASMIN E VICTOR NO MUNDO DA LOUCURA", "ROMANCE", "18");
INSERT INTO FILMES (TITULO ,GENERO  ,CENSURA) VALUES("IASMIN II A SALVAÇÃO DO MUNDO", "DRAMA", "14");
INSERT INTO FILMES (TITULO ,GENERO  ,CENSURA) VALUES("O CAVALEIRO KLOVIZ", "AÇÃO", "14");
INSERT INTO FILMES (TITULO ,GENERO  ,CENSURA) VALUES("UM AMOR E UM CACHORRO", "ROMANCE", "LIVRE");

SELECT * FROM FILMES;


INSERT INTO SESSAO( FILMES_idFILMES,CINEMA_idCINEMA,DATA_HORA,PRECO) values (1,2,"2024-16-04-10:55", 30.50);
update SESSAO set DATA_HORA = "2024-04-16-10:55:00" where idSESSAO = 1;
INSERT INTO SESSAO( FILMES_idFILMES,CINEMA_idCINEMA,DATA_HORA,PRECO) values (2,1,"2024-04-17-10:55", 35.50);
INSERT INTO SESSAO( FILMES_idFILMES,CINEMA_idCINEMA,DATA_HORA,PRECO) values (4,3,"2024-04-16-10:55:00", 30.50);
INSERT INTO SESSAO( FILMES_idFILMES,CINEMA_idCINEMA,DATA_HORA,PRECO) values (3,4,"2024-05-18-10:00:00", 32.00);
INSERT INTO SESSAO( FILMES_idFILMES,CINEMA_idCINEMA,DATA_HORA,PRECO) values (5,5,"2024-05-19-11:00:00", 22.00);
SELECT * FROM SESSAO;

INSERT INTO CLIENTES( NOME ,CPF  ,SEXO ,DATA_NASCIMENTO ) VALUES ("VICTOR", "99923554371", "M", "2004-05-19" );
INSERT INTO CLIENTES( NOME ,CPF  ,SEXO ,DATA_NASCIMENTO ) VALUES ("IASMIN", "76565798765", "F", "2005-03-15" );
INSERT INTO CLIENTES( NOME ,CPF  ,SEXO ,DATA_NASCIMENTO ) VALUES ("SHIRLEY", "77565898762", "F", "2023-07-18" );
INSERT INTO CLIENTES( NOME ,CPF  ,SEXO ,DATA_NASCIMENTO ) VALUES ("SAMUEL", "88565098763", "M", "2006-04-17" );
INSERT INTO CLIENTES( NOME ,CPF  ,SEXO ,DATA_NASCIMENTO ) VALUES ("RODRIGO", "00565898778", "M", "2006-12-29" );
SELECT * FROM CLIENTES;

INSERT INTO COMPRAS ( SESSAO_idSESSAO ,CLIENTES_idCLIENTES  ,QUANTIDAE_INTEIRA  ,QUANTIDAE_MEIA ,FORMA_PAGAMENTO ) VALUES (1,1,1,0,"PIX");
INSERT INTO COMPRAS ( SESSAO_idSESSAO ,CLIENTES_idCLIENTES  ,QUANTIDAE_INTEIRA  ,QUANTIDAE_MEIA ,FORMA_PAGAMENTO ) VALUES (2,2,0,5,"DÉBITO");
INSERT INTO COMPRAS ( SESSAO_idSESSAO ,CLIENTES_idCLIENTES  ,QUANTIDAE_INTEIRA  ,QUANTIDAE_MEIA ,FORMA_PAGAMENTO ) VALUES (3,3,2,0,"CREDITO");
INSERT INTO COMPRAS ( SESSAO_idSESSAO ,CLIENTES_idCLIENTES  ,QUANTIDAE_INTEIRA  ,QUANTIDAE_MEIA ,FORMA_PAGAMENTO ) VALUES (4,5,1,1,"PIX");
INSERT INTO COMPRAS ( SESSAO_idSESSAO ,CLIENTES_idCLIENTES  ,QUANTIDAE_INTEIRA  ,QUANTIDAE_MEIA ,FORMA_PAGAMENTO ) VALUES (5,4,1,0,"DÉBITO");
DELETE FROM COMPRAS WHERE idCOMPRAS = 2;


SELECT * FROM COMPRAS;

ALTER TABLE CINEMA ADD NUMERO_CADEIRA INTEGER;

ALTER TABLE CLIENTES CHANGE COLUMN DATA_NASCIMENTO NASCIMENTO DATE;

ALTER TABLE CLIENTES drop COLUMN CPF;
